export default [
    {
        id: '1',
        title: 'Title 1',
        desc: 'des description description description description description description description description description description description description description description description',
        thumbnail: 'https://cdn.pixabay.com/photo/2024/02/23/08/27/apple-8591539_1280.jpg',
        category: 'breaking-news',
    },
    {
        id: '2',
        title: 'Title 2',
        desc: 'des description description description description description description description description description description description description description description description',
        thumbnail: 'https://cdn.pixabay.com/photo/2018/07/20/14/02/grapes-3550733_1280.jpg',
        category: 'breaking-news',
    },
    {
        id: '3',
        title: 'Title 3',
        desc: 'des description description description description description description description description description description description description description description description',
        thumbnail: 'https://cdn.pixabay.com/photo/2015/05/04/10/16/vegetables-752153_1280.jpg',
        category: 'breaking-news',
    },
    {
        id: '4',
        title: 'Title 4',
        desc: 'des description description description description description description description description description description description description description description description',
        thumbnail: 'https://cdn.pixabay.com/photo/2016/04/02/04/14/bell-peppers-1302126_1280.jpg',
        category: 'breaking-news',
    },
    {
        id: '5',
        title: 'Title 5',
        desc: 'des description description description description description description description description description description description description description description description',
        thumbnail: 'https://cdn.pixabay.com/photo/2023/03/20/10/04/buns-7864270_1280.jpg',
        category: 'tech',
    },
    {
        id: '6',
        title: 'Title 6',
        desc: 'des description description description description description description description description description description description description description description description',
        thumbnail: 'https://cdn.pixabay.com/photo/2017/11/18/17/09/strawberries-2960533_1280.jpg',
        category: 'tech',
    },
    {
        id: '7',
        title: 'Title 7',
        desc: 'des description description description description description description description description description description description description description description description',
        thumbnail: 'https://cdn.pixabay.com/photo/2016/05/31/13/01/raspberries-1426859_1280.jpg',
        category: 'tech',
    },
    {
        id: '8',
        title: 'Title 8',
        desc: 'des description description description description description description description description description description description description description description description',
        thumbnail: 'https://cdn.pixabay.com/photo/2016/05/31/13/01/raspberries-1426859_1280.jpg',
        category: 'political',
    },
    {
        id: '9',
        title: 'Title 9',
        desc: 'des description description description description description description description description description description description description description description description',
        thumbnail: 'https://cdn.pixabay.com/photo/2016/05/31/13/01/raspberries-1426859_1280.jpg',
        category: 'political',
    },
    {
        id: '10',
        title: 'Title 10',
        desc: 'des description description description description description description description description description description description description description description description',
        thumbnail: 'https://cdn.pixabay.com/photo/2016/05/31/13/01/raspberries-1426859_1280.jpg',
        category: 'political',
    },
    {
        id: '11',
        title: 'Title 11',
        desc: 'des description description description description description description description description description description description description description description description',
        thumbnail: 'https://cdn.pixabay.com/photo/2016/05/31/13/01/raspberries-1426859_1280.jpg',
        category: 'entertainment',
    },
    {
        id: '12',
        title: 'Title 12',
        desc: 'des description description description description description description description description description description description description description description description',
        thumbnail: 'https://cdn.pixabay.com/photo/2016/05/31/13/01/raspberries-1426859_1280.jpg',
        category: 'entertainment',
    },
    {
        id: '13',
        title: 'Title 13',
        desc: 'des description description description description description description description description description description description description description description description',
        thumbnail: 'https://cdn.pixabay.com/photo/2016/05/31/13/01/raspberries-1426859_1280.jpg',
        category: 'entertainment',
    },
]